title: $$\LaTeX-savvy$$
email: imb2139@columbia.edu
description: >-
  A few guides to get you started with the LaTeX environment.
baseurl: "/latex-savvy"
url: ""
github_username:  basseches

# Build settings
theme: minima
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: "assets/static"
    values:
      image: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
